import type { Metadata } from "next";
import "@/app/globals.css";

import { Inter } from "next/font/google";
import HeaderServer from "@/components/header/HeaderServer";
import Footer from "@/components/Footer";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com" rel="preconnect" />
        <link href="https://fonts.gstatic.com" rel="preconnect" />

        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.variable} antialiased`}>
        <NextTopLoader
          color="#2299DD" // Màu của thanh loading (thay bằng màu primary của bạn)
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false} // Tắt cái vòng xoay xoay ở góc, chỉ để thanh ngang cho đẹp
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        <HeaderServer />
        {children}

        <Footer />
      </body>
    </html>
  );
}
